version: "3"
services:
  db:
    image: postgres:16
    ports:
      - "5476:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: ledger
      POSTGRES_DB: ledger
